#define MSGCOUNT 5

int ClassPickupMessages[CLASSCOUNT][SLOTCOUNT][MSGCOUNT] = 
{
    {
        {
            "I PUNCH YOO",
            "\cgRIP AND TEAR",
            "",
            "",
            "",
        },
        {
            "A chainsaw! Find some meat!",
            "The great communicator!",
            "",
            "",
            "",
        },
        {
            "Picked up a pistol.",
            "Hey, useless!",
            "",
            "",
            "",
        },
        {
            "You got the Shotgun!",
            "Might makes light!",
            "",
            "",
            "",
        },
        {
            "You got the Super Shotgun!",
            "And I feel mighty!",
            "",
            "",
            "",
        },
        {
            "You got the Chaingun!",
            "Hey, chaingun! The hell with respect!",
            "",
            "",
            "",
        },
        {
            "You got the Rocket Launcher!",
            "The sugar-sweet kiss of heavy ordinance!",
            "",
            "",
            "",
        },
        {
            "You got the Plasma Rifle!",
            "Sweet christmas! It's always something!",
            "",
            "",
            "",
        },
        {
            "You got the BFG9000! Oh, yes.",
            "Hail to the chief!",
            "",
            "",
            "",
        },
    },
    {   // yeah I really didn't have ideas for this one
        {
            "I SCOOP YOO",
            "\cdPOUR AND SHARE",
            "",
            "",
            "",
        },
        {
            "A Super Bootspork! Find some milk!",
            "I'm pretty sure this wasn't made for boots.",
            "",
            "",
            "",
        },
        {
            "Picked up a Mini Zorcher.",
            "Hey, useless zappy thing!",
            "",
            "",
            "",
        },
        {
            "You got the Large Zorcher!",
            "Why do zappy things need spread again?",
            "",
            "",
            "",
        },
        {
            "You got the Super Large Zorcher!",
            "Bouncy death in a white box!",
            "",
            "",
            "",
        },
        {
            "You got the Rapid Zorcher!",
            "Wasn't this an eggbeater?",
            "",
            "",
            "",
        },
        {
            "You got the Zorch Propulsor!",
            "No rocket jumping for you.",
            "",
            "",
            "",
        },
        {
            "You got the Phasing Zorcher!",
            "Zappy red things!",
            "",
            "",
            "",
        },
        {
            "You got the LAZ Device! Woot!",
            "The pinnacle of science. Giant red blobs of zap.",
            "",
            "",
            "",
        },
    },
    {
        {
            "I JAB YOO",
            "\cfBEAT AND PARRY",
            "",
            "",
            "",
        },
        {
            "Gauntlets of the Necromancer! Find some disciples!",
            "The gloves your gloves wish they were.",
            "",
            "",
            "",
        },
        {
            "Picked up a gold wand.",
            "Hey, useless crystal thing!",
            "",
            "",
            "",
        },
        {
            "You got the Firemace!",
            "And you thought this was Slot 7.",
            "",
            "",
            "",
        },
        {
            "You got the Ethereal Crossbow!",
            "Aren't crossbows meant to be accurate?",
            "",
            "",
            "",
        },
        {
            "You got the Dragon Claw!",
            "So apparently dragons are walking miniguns?",
            "",
            "",
            "",
        },
        {
            "You got the Phoenix Rod!",
            "Also doubles as a shitty coat rack.",
            "",
            "",
            "",
        },
        {
            "You got the Hellstaff!",
            "It's too close to a plasma rifle. UAC's gonna sue.",
            "",
            "",
            "",
        },
        {
            "You got the Tome of Power! Ahahaha...",
            "Fuck BFG, we'll make \caeverything\c- overpowered.",
            "",
            "",
            "",
        },
    },
    {
        {
            "I STAB YOO",
            "\cgSTAB AND SPAR",
            "",
            "",
            "",
        },
        {
            "Your knife developed teeth! Find some Nazis!",
            "Now \cathis\c- is a knife!",
            "",
            "",
            "",
        },
        {
            "Picked up a Luger.",
            "Hey, sniper useless!",
            "",
            "",
            "",
        },
        {
            "You got the Machine Gun!",
            "Shotgun? Fuck off, I've got a machine gun.",
            "",
            "",
            "",
        },
        {
            "You got the Machine Gun!",
            "Super shotgun? Ahahaha no.",
            "",
            "",
            "",
        },
        {
            "You got the Chaingun!",
            "If this were Wolf3D, you'd just have hit top tier.",
            "",
            "",
            "",
        },
        {
            "You got the Rocket Launcher!",
            "You got the Zreep Gun!",
            "",
            "",
            "",
        },
        {
            "You got the Flamethrower!",
            "Because flamethrowers have infinite range.",
            "",
            "",
            "",
        },
        {
            "You got the Spear of Destiny! Heaven awaits.",
            "Buttered popcorn, straight from Jesus.",
            "",
            "",
            "",
        },
    },
    {
        {
            "I WAK YOO",
            "\cfPOUND AND SMEAR",
            "",
            "",
            "",
        },
        {
            "Flechettes! Find some centaurs!",
            "Mexican burritos would be more effective.",
            "",
            "",
            "",
        },
        {
            "Picked up a sapphire wand.",
            "Hey, actually slightly useful!",
            "",
            "",
            "",
        },
        {
            "You got the Frost Shards!",
            "You got the Massive Weapon Frost-wait what.",
            "",
            "",
            "",
        },
        {
            "You got Timon's Axe!",
            "Because whacking people with an axe needs lightning.",
            "",
            "",
            "",
        },
        {
            "You got the Serpent Staff!",
            "CLERIC SAPPIN MAH CENTAUR",
            "",
            "",
            "",
        },
        {
            "You got the Hammer of Retribution!",
            "Infinite amounts of exploding hammers. Okay then.",
            "",
            "",
            "",
        },
        {
            "You got the Firestorm!",
            "Literal baptism by fire.",
            "",
            "",
            "",
        },
        {
            "You got the Wraithverge! Scream for me!",
            "Still less powerful than a fart cloud.",
            "",
            "",
            "",
        },
    },
    {
        {
            "I KICK YOO",
            "Balls of steel, meet boots of steel.",
            "",
            "",
            "",
        },
        {
            "Pipe bombs! Find some unsuspecting saps!",
            "Enjoy \cathis\c- present.",
            "",
            "",
            "",
        },
        {
            "Picked up an M1911.",
            "Counterpoint number 1.",
            "",
            "",
            "",
        },
        {
            "You got the Riot Shotgun!",
            "I hope you like buckshot for lunch.",
            "",
            "",
            "",
        },
        {
            "You got the Explosive Shotgun!",
            "This'll satisfy my appetite for \cgDEATH\c-.",
            "",
            "",
            "",
        },
        {
            "You got the Chaingun Cannon!",
            "Oh dear, you're coming apart at the seams!",
            "",
            "",
            "",
        },
        {
            "You got the RPG Launcher!",
            "When I'm through, the walls will be a memorial of your interiors.",
            "",
            "",
            "",
        },
        {
            "You got the Freezethrower!",
            "Stopped you dead in your tracks, didn't I?",
            "",
            "",
            "",
        },
        {
            "You got the Devastators! Hail to the King.",
            "Game over, chumps.",
            "",
            "",
            "",
        },
    },
    {
        {
            "I PUNCH YOO TOO",
            "Run sideways, oneshot imp. Got it.",
            "",
            "",
            "",
        },
        {
            "A KKV-7 SMG and an extra .44 Magnum! Find some aliens!",
            "I'm gonna go cowboy on your ass.",
            "",
            "",
            "",
        },
        {
            "Picked up a magnum.",
            "HOW I HOLD NOTHER PSITOL I DUNO LOL",
            "",
            "",
            "",
        },
        {
            "You got the WSTE-M5 Combat Shotgun!",
            "I'm gonna make an expressway to your heart.",
            "",
            "",
            "",
        },
        {
            "You got the Zeus Class Fusion Pistol!",
            "Oh, you're invulnerable? That's cute.",
            "",
            "",
            "",
        },
        {
            "You got the MA-75B Assault Rifle!",
            "I'll suppress you forever.",
            "",
            "",
            "",
        },
        {
            "You got the SPNKR-XP SSM Launcher!",
            "The janitors will hate me today.",
            "",
            "",
            "",
        },
        {
            "You got the TOZT-7 Napalm Unit!",
            "Who wants a barbeque?",
            "",
            "",
            "",
        },
        {
            "You got the ONI-71 Wave Motion Cannon! What's that spell? Trouble.", // since apparently this quote ain't good enuf
            "I'm returning you to the store in a coffee tin.",
            "",
            "",
            "",
        },
    },
};
