#define MSGCOUNT 10

int ClassPickupMessages[CLASSCOUNT][SLOTCOUNT][MSGCOUNT] = 
{
    {
        {
            "I PUNCH YOO",
            "\cgRIP AND TEAR",
            "Fuck your handshakes.",
            "No, you can't do Fatalities. Stop asking.",
            "Rule #1 - do not talk about Fight Club.",
            "You got a pair of hands!",
            "Um... they were in your other pair of pants.",
            "",
            "",
            "",
        },
        {
            "A chainsaw! Find some meat!",
            "The great communicator!",
            "Groovy.",
            "Warning: Welding to hand may be hazardous to health.",
            "Tearfully, you realize you can finally enact your secret lumberjack fantasies.",
            "Go ahead, chuckles, charge those gunmen.",
            "Well, normally I would rip and tear, but that just seems so barbaric.",
            "When you have a chainsaw, everything starts looking like a tree.",
            "Be careful when sheathing this.",
            "It makes a terrible unicycle.",
        },
        {
            "Picked up a pistol.",
            "Hey, useless!",
            "The most useless pistol in this mod.",
            "Wait, how are you even seeing this?",
            "Picked up two clips... wait.",
            "Sounds like a bag popping.",
            "",
            "",
            "",
            "",
        },
        {
            "You got the Shotgun!",
            "Might makes light!",
            "Fuck vertical spread.",
            "Eat leaden death, demon...",
            "Good, bad. I'm the guy with the gun.",
            "Clearly this solves all your problems.",
            "Duck season! Fire!",
            "Tape two side by side, still not as good as the SSG.",
            "I think I saw this in the toy aisle...",
            "The UAC has forgone auto-shotguns in favor of...uh. This.",
        },
        {
            "You got the Super Shotgun!",
            "And I feel mighty!",
            "The only Slot 3 allowed to get away with 200 damage.",
            "Where do the extra six pellets come from? Your pecs.",
            "The souls of a million DWANGO5 marines resonate from within...",
            "Clearly this solves even more problems.",
            "Time to ignore your normal shotgun now.",
            "In which centuries of weapon development are ignored for a western coachgun.",
            "Suddenly, you discovered vertical spread.",
            "You're not stuffing the shells in the front of the barrel, are you?",
        },
        {
            "You got the Chaingun!",
            "Hey, chaingun! The hell with respect!",
            "It's not like you were using that ammo for anything else...",
            "Does not actually shoot chains.",
            "Real men use handheld gatling guns.",
            "Spingun acquired.",
            "No speed debuff needed.",
            "omg it spins dicks",
            "You spin me right 'round baby right round.",
            "Who thought it would be a good idea to mount a gatling on a rifle?",
        },
        {
            "You got the Rocket Launcher!",
            "The sugar-sweet kiss of heavy ordinance!",
            "Still the best rocket jumping tool.",
            "Point away from face and fire.",
            "\cfRAWKET LAWNCHAIR!",
            "FOONT! noise sold seperately.",
            "Gonna tell 'em with this, soldier boy?",
            "The noob toob from 20 years past.",
            "On this week's Did You Know Gaming: Doom explosions are square.",
            "Lodged right in the middle of the chest for easier firing.",
        },
        {
            "You got the Plasma Rifle!",
            "Sweet christmas! It's always something!",
            "All reet then! I'm all about this plasma rifle!",
            "I'm all about this plasma rifle! And baby, it's all about me!",
            "John gotted his palsma rifle.",
            "What're you gonna do, give them high definition TVs?",
            "Hit 1.21 gigawatts and you're gonna see some serious shit.",
            "You got a backwards M60-style dart gun!",
            "The recoil only kicks in after you let go of the trigger. How shitty!",
            "Kickback's the same whether you fire for one shot or 100.",
        },
        {
            "You got the BFG9000! Oh, yes.",
            "Hail to the chief!",
            "... and my gun is very, very large.",
            "Guaranteed to make lots of friends.",
            "omg op hax gay nerf ban",
            "Ukraine called, they want their fuel rods back.",
            "What is this sublety you speak of?",
            "It's actually a calculator, it just has a terrible overheating problem.",
            "So how does A_BFGSpray work in-universe, anyway?",
            "Two hits. First the ball hits you. Then my body odor hits you.",
        },
        {
            "A chainsaw! Find some meat!",
            "The great communicator!",
            "Groovy.",
            "Warning: Welding to hand may be hazardous to health.",
            "Tearfully, you realize you can finally enact your secret lumberjack fantasies.",
            "Go ahead, chuckles, charge those gunmen.",
            "Well, normally I would rip and tear, but that just seems so barbaric.",
            "When you have a chainsaw, everything starts looking like a tree.",
            "Be careful when sheathing this.",
            "It makes a terrible unicycle.",
        },
    },
    {
        {
            "I SCOOP YOO",
            "\cdPOUR AND SHARE",
            "SPOOOOOOOOOOOON!",
            "No wonder the IFOC relies more on zorchers.",
            "Zorch his heart out with a spoon!",
            "",
            "",
            "",
            "",
            "",
        },
        {
            "A Super Bootspork! Find some milk!",
            "I'M A FUCKING \cgWAFFLE!",
            "I will scoop out your organs and serve them for breakfast.",
            "Drilling with the sharp and pointy ends doesn't kill. Who knew?",
            "Makes a mess out of soups.",
            "Protip: goes in your hand, genius.",
            "Horribly slow murderer, meet extremely inefficient weapon.",
            "In the future, you have to cyberneticize everything.",
            "These guys looked at food utensils, then decided 'We should weaponize this'.",
            "It makes a terrible salad mixer.",
        },
        {
            "Picked up a Mini Zorcher.",
            "Hey, useless zappy thing!",
            "I think this is broken. It doesn't change the channel.",
            "The only way you'd see this message is by being a dirty cheater.",
            "How come Chex squadron never let any of the Kix guys in? That's racist.",
            "",
            "",
            "",
            "",
            "",
        },
        {
            "You got the Large Zorcher!",
            "Why do zappy things need spread again?",
            "Actually larger than the Super Large Zorcher.",
            "Man, dude reloads faster than a motherfucker.",
            "Poor thing never gets any use later on.",
            "Great for raves and children's parties!",
            "I lost my flashlight, can I borrow yours?",
            "Operates off the same ammo as the SLZ. Works in an entirely different way.",
            "Kid-tested, mother-approved.",
            "It's terrible for search and rescue.",
        },
        {
            "You got the Super Large Zorcher!",
            "Bouncy death in a white box!",
            "In case you thought the railgun needed a bit more bounce.",
            "Four times the family-friendly entertainment.",
            "No longer a HacX taser rip.",
            "Comes with three-patty burger and an assload of fries.",
            "ORIGINAL CHARACTER DO NOT STEAL",
            "Jacobi sure had some weird ideas about how an SSG clone should work.",
            "No, you can't use it to boost your Wi-Fi signal.",
            "Why doesn't this damn modem work?!",
        },
        {
            "You got the Rapid Zorcher!",
            "Wasn't this an eggbeater?",
            "This one needs \cdTWO\c- buttons!",
            "The NES controller of doo--uh, zorch.",
            "Spinning nodes do not contribute well to hypnotism.",
            "Rapid is a fancy word for goodbye ammo.",
            "It makes for a terrible lockpick.",
            "The quality of the back massage makes up for the length of it.",
            "",
            "",
        },
        {
            "You got the Zorch Propulsor!",
            "No rocket jumping for you.",
            "w+m1",
            "So it's a melee weapon, right?",
            "I'm sure the DONTHURTSHOOTER flag will have no negative repurcussions.",
            "A farewell to harms.",
            "Can tear a Cyberdemon to shreds. Can't open doors.",
            "omg snot bubble gun",
            "",
            "",
        },
        {
            "You got the Phasing Zorcher!",
            "Zappy red things!",
            "Look, ma, three fingers.",
            "Push button, recieve carnage.",
            "I hear the balls taste like candy if you eat them. Best to try it on incoming idiots first.",
            "I dunno, those guys don't seem too phased by it.",
            "You're like a futuristic pitching machine.",
            "Awww, I only get cherry Skittles.",
            "",
            "",
        },
        {
            "You got the LAZ Device! Woot!",
            "Remember when this gibbed people? Pepperidge Farm remembers.",
            "No longer a BFG9000 ripoff, now it's just a fancy rocket launcher.",
            "The IFOC don't believe in overzorch.",
            "Yeah, sure, I'll defend you with this. You go on ahead.",
            "Add a Y to the acronym, won't you?",
            "Even if you miss, it's almost guaranteed to hit.",
            "Mother-tested, kid-approved.",
            "In the end, don't we all have a little LAZ Device, in our hearts?",
            "Because 'I like pretty lights' is as good a justification as any.",
        },
        {
            "A Super Bootspork! Find some milk!",
            "I'M A FUCKING \cgWAFFLE!",
            "I will scoop out your organs and serve them for breakfast.",
            "Drilling with the sharp and pointy ends doesn't kill. Who knew?",
            "Makes a mess out of soups.",
            "Protip: goes in your hand, genius.",
            "Horribly slow murderer, meet extremely inefficient weapon.",
            "In the future, you have to cyberneticize everything.",
            "These guys looked at food utensils, then decided 'We should weaponize this'.",
            "It makes a terrible salad mixer.",
        },
    },
    {
        {
            "I JAB YOO",
            "\cfBEAT AND PARRY",
            "Occasionally makes blue explosions where it hits.",
            "More magic wands need to be used to beat people senseless.",
            "If you make any jokes about wood and beating, I will cut you.",
            "Whap whap whap.",
            "",
            "",
            "",
            "",
        },
        {
            "Gauntlets of the Necromancer! Find some disciples!",
            "The gloves your gloves wish they were.",
            "No! No! Anything but cold metal!",
            "Note: Does not actually raise the dead.",
            "Force lightning on command.",
            "Quit touching dead people, that's not what they do!",
            "Great for riding motorcyles too!",
            "They're actually kind of a bitch to take on and off. Stop swapping so fast.",
            "They come with built-in guitar picks.",
            "It's hot and cold at the same time!",
        },
        {
            "Picked up a gold wand.",
            "Hey, useless crystal thing!",
            "Pew pew pew.",
            "The elven community frowns upon your cheating shenanigans.",
            "SPARKLIES!",
            "",
            "",
            "",
            "",
            "",
        },
        {
            "You got the Firemace!",
            "So how does this thing accept ammo, anyway?",
            "I've got balls of steel.",
            "Eheheheh. It fires metal spheres.",
            "The most useless ultimate in all of idtech1.",
            "Fun fact: skeeball is Corvus' favorite game.",
            "Just go ahead and start swinging. Damn thing won't break.",
            "Cherish your enemy's faces upon realizing they're about to experience death by balls.",
            "You got a sack for all those balls?",
            "The damage you inflict decreases exponentially with every penis joke.",
        },
        {
            "You got the Ethereal Crossbow!",
            "Honestly? A piece of wood with a groove in it would work.",
            "Well of course the bolts are slow! Nothing's pushing on them!",
            "It's a spook-shooting bow.",
            "Only partly ethereal energy hits ghosts. What?",
            "Iiiii aaaam the ghoooost boooolt! WHOOOO!",
            "So haunted it belongs on eBay.",
            "Gravity is stupid.",
            "If it's ethereal, how do you hold it?",
            "No, it's not that type of ether. Stop trying to huff the bolts.",
        },
        {
            "You got the Dragon Claw!",
            "So apparently dragons are walking miniguns?",
            "Great for kebabs!",
            "Here, gimme a hand.",
            "DRAGON CLAW: Now $8.99 at Jade King's Palace!",
            "Now you can finally reach that itch.",
            "Dungeons not included.",
            "Claws work best when they don't touch the ground, right?",
            "It makes a terrible mitten, surprisingly.",
            "It could be a great melee weapon, but no, can't have that. Stupid elfs.",
        },
        {
            "You got the Phoenix Rod!",
            "Also doubles as a coat rack. Assuming the coats are fireproof.",
            "Flip someone the bird tonight.",
            "You will believe shooting a bird can recoil.",
            "Bring your enemies back from the ashes.",
            "Polly wanna toast bad guys? Yes you do!",
            "You could put a soul out with that thing.",
            "It's not actually real gold. They just spraypainted it.",
            "You know, practically all of these would be great for clobbering someone.",
            "I'll resurrect you. Uh. Eventually.",
        },
        {
            "You got the Hellstaff!",
            "It's too close to a plasma rifle. UAC's gonna sue.",
            "Like the plasma rifle, but shittier in every way.",
            "Time to rain on someone's parade.",
            "omg satan gun",
            "Turn PG mode on and it's the Heckstick.",
            "The only weapon to survive Heretic 2.",
            "I'm not sure how I feel about this new take on pitchforks.",
            "You got the bonerstaff!",
            "Clubbing people with the skull is not advised.",
        },
        {
            "You got the Tome of Power! Ahahaha...",
            "For a last ditch effort, you can always throw it.",
            "Yeah, it's cool how your glove fires spiky balls. Now try actually reading it.",
            "Little known fact: LeVar Burton was actually a wizard.",
            "Only actually seven of these things? Tyketto was a dick for a Seraph.",
            "I didn't play a damn FPS to read!",
            "Death of a thousand papercuts!",
            "Be ye magicked, bitches.",
            "I'm totally going to kick your ass, guys, just let me finish this paragraph.",
            "It's actually a romance novel. The 'power' refers to something else entirely.",
        },
        {
            "Gauntlets of the Necromancer! Find some disciples!",
            "The gloves your gloves wish they were.",
            "No! No! Anything but cold metal!",
            "Note: Does not actually raise the dead.",
            "Force lightning on command.",
            "Quit touching dead people, that's not what they do!",
            "Great for riding motorcyles too!",
            "They're actually kind of a bitch to take on and off. Stop swapping so fast.",
            "They come with built-in guitar picks.",
            "It's hot and cold at the same time!",
        },
    },
    {
        {
            "I STAB YOO",
            "\cgSTAB AND SPAR",
            "Poke 'em. Go on. Do it.",
            "Rule #2 - Do \cgNOT\c- talk about Fight Club.",
            "Pew pew pew.",
            "",
            "",
            "",
            "",
            "",
        },
        {
            "Your knife got thicker! Find some Nazis!",
            "Now \cathis\c- is a knife!",
            "You can bring this one to a gun fight.",
            "It's a food utensil, I swear.",
            "Who needs a special key for knifing, anyway?",
            "Because a huge guy with a little knife isn't nearly as scary as a little guy with a huge knife.",
            "Good for one Nazi. Bad for one hundred.",
            "I'm having a cutlery party and you're invited!",
            "Who said you can't lose weight with an overactive knife?",
            "So, who decided to let the guy in prison have a fuckoff knife?",
        },
        {
            "Picked up a Luger.",
            "Hey, sniper useless!",
            "Of course a pistol would be more accurate than most modern assault rifles.",
            "Nazis sure knew how to make their pistols.",
            "No, seriously, why are you such a cheating hack?",
            "",
            "",
            "",
            "",
            "",
        },
        {
            "You got the Machine Gun!",
            "Or it could be a silver waffle cone that fires bullets. Your choice.",
            "Basically a faster, weaker sniper rifle.",
            "Actually more of an assault rifle, but...",
            "It's better than the Doomguy's chaingun. How does that even work.",
            "Hold it properly like real gangsters do.",
            "You got a piece of rust shaped like a machine gun!",
            "Oh my god, this game rips off Call of Duty so much.",
            "Flamethrowers, machineguns, and chemical bombs are okay. Shotguns? \cgDisgusting.\c-",
            "",
        },
        {
            "You got the Machine Gun!",
            "Nah.",
            "Well, time to stay the hell away from the dude with the SSG.",
            "No, there will not be a different slot III.",
            "And now for something completely the same.",
            "It's also licensed for weight loss.",
            "Wait, didn't I just get this?",
            "Now you still can't dual wield them.",
            "Come on. Silver waffle cone. You know you want it.",
            "",
        },
        {
            "You got the Chaingun!",
            "If this were Wolfenstein 3D, you'd just have hit top tier.",
            "A constant beam of death from any range. Not bad.",
            "Actually more of a gatling gun, but...",
            "Why is it turquoise?!",
            "Hope you like ammo scrounging!",
            "The as-salt to the machine gun's pepper.",
            "Oh my god, this game rips off Doom so much.",
            "",
            "",
        },
        {
            "You got the Rocket Launcher!",
            "You got the Zreep Gun!",
            "I don't think Wolfenstein 3D really understood rocket launchers.",
            "Yes, it existed. It was in the Mac version.",
            "Yes, it explodes. A little bit. Shut up.",
            "The tube is clogged. Is that a bad thing?",
            "It's like a launchable wood chipper.",
            "So, Hans, let me get this straight. You decided to make a gun that shoots drills.",
            "You will believe a rocket can rip and tear.",
            "You got a penis extender.",
        },
        {
            "You got the Flamethrower!",
            "Because flamethrowers have infinite range.",
            "We're trying to avoid the obvious jokes.",
            "You got a lifetime supply of Viagra! Wait, what?!",
            "Yes indeed, it werfs flammens.",
            "God damn this stupid thing is so heavy.",
            "Pretty sure these are tomatoes.",
            "Are we fighting demons, or are we fighting unfunny comedians?",
            "Pulled straight out of Vampire Hitler's chest.",
            "but the flamethrower ripped in the snes port this is so inaccurate how could you do this you terrible people stop modding kill yourself",
        },
        {
            "You got the Spear of Destiny! Heaven awaits.",
            "Buttered popcorn, straight from Jesus.",
            "Delicious overpoweredness. What more could you want?",
            "If a weapon stabs Jesus, it becomes superpowered. Who knew?",
            "\cfYOU MAY WIELD THE SPEAR...",
            "Poke Of Kill Everything.",
            "You know you're supposed to throw it, right?",
            "I bet it has fake butter, though.",
            "But the Spear of Destiny was inside you all along.",
            "It makes a terrible melee weapon. Surprisingly.",
        },
        {
            "Your stabbing arm got faster! Find even more Nazis!",
            "All those years of karate... useless.",
            "This required a new knife?",
            "pew pew pew pew pew pew pew",
            "Unfortunately, your secret peanut butter spread techniques must now be used for violence.",
            "",
            "",
            "",
            "",
            "",
        },
    },
    {
        {
            "I WAK YOO",
            "\cfPOUND AND SMEAR",
            "Clerics used maces because shedding blood was against their code of conduct. Okay.",
            "I'm battin' a million here!",
            "Not too hot for flagellation, turns out.",
            "More accurate than the Axe.",
            "",
            "",
            "",
            "",
        },
        {
            "Flechettes! Find some centaurs!",
            "Expiration dates are just suggestions. Drink it anyway.",
            "This is just a fart in a flask!",
            "Do not attempt to drink.",
            "Do you want to know how long this has been fermenting?",
            "Brought to you by Mace Cologne-inna-bottle for Gents!",
            "Don't yell 'Fire in the Hole'. Too cliche.",
            "I'm pretty sure this isn't a healing potion.",
            "No, it is not a protein shake.",
            "Grandma's special ingredient.",
        },
        {
            "Picked up a sapphire wand.",
            "Hey, actually slightly useful!",
            "This is all you need to slaughter Korax.",
            "BEEMS",
            "I'm going to call your mother and tell her what you've been doing.",
            "",
            "",
            "",
            "",
            "",
        },
        {
            "You got the Frost Shards!",
            "You got the Massive Wanker Frost!",
            "Dammit, put your pants back on! That's stupid!",
            "Reach out and touch somebody.",
            "Popsicles. Now in \cgDEATH\c- flavor.",
            "Melts in your hand, not in your enemy.",
            "Sno-Cones to go, just add corpse.",
            "I'll literally crack your brain.",  // Holy Diver - Gypsy
            "Such an icy temper.",
            "It makes for a terrible masseuse technique.",
        },
        {
            "You got Timon's Axe!",
            "Bringing the thunder!",
            "Well, you'd be in melee range \caanyway\c-...",
            "Thou shalt not kill unless thou art fucking metal.",
            "'Dat lightning ain't a special effect, kiddo!",
            "Bow, sword and One Ring quest sold seperately.",
            "It means no worries.",
            "You are evil, I am divine.",
            "You got a big piece of metal that kills things.",
            "If you're asking questions, you're not using enough axe.",
        },
        {
            "You got the Serpent Staff!",
            "The eye always watches. Even when it doesn't want to. You sicko.",
            "Serpents are secretly vampires. Got it.",
            "Dude, not in public.",
            "The eye... it stares into my soul...",
            "Had to paralyze this damn thing to stop it from wiggling.",
            "I put a spell on you, 'cuz you're miiiine.",
            "I only need one evil eye.",  // The Last in Line - Evil Eyes
            "Spread the gospel of heavy metal. Poison the shit out of everyone in the way.",
            "Great for sucking, but spits lots of venom. Just like your ex.",
        },
        {
            "You got the Hammer of Retribution!",
            "Infinite amounts of exploding hammers. Okay then.",
            "I think this weapon breaks the law of conservation of mass.",
            "You can't get more metal than a flaming hammer.",
            "\\\\m/         \\\\m/",
            "Feeling Thor? Get thome athpirin.",
            "Careful, you'll give Games Workshop some ideas.",
            "Strength in numbers? Ha! Your number is \canone\c-.",  // Dehumaniser - I
            "Great for bubble wrap!",
            "Hammerfall would be proud.",
        },
        {
            "You got the Firestorm!",
            "Literal baptism by fire.",
            "So manly, your arms spontaneously grow chainmail.",
            "Raise your hands in the air, wave 'em like you just don't care.",
            "Most unnecessarily roundabout damage method in the game.",
            "Inflammable means flammable? What a country!",
            "Stop your enemy, drop them, roll on their graves.",
            "You can release yourself, but the only way is \cadown under\c-.",  // The Last in Line
            "And give me an amen. Let's start! \crAIIIYYEEEEEE-",
            "Spitting flames so hot it burns hellfire.",
        },
        {
            "You got the Wraithverge! Scream for me!",
            "It kills video games, too.",
            "Ahahahaha aiming. Fuck that.",
            "Praise the Lord and pass the screaming angry souls of the damned.",
            "The ultimate in pope-based weaponry. You know you're holy when the tortured spirits of hell bow to your will.",
            "Don't look at the Ark, Marion! Close your eyes!",
            "Ten seconds ago it was the Wraithalmostthereholdon.",
            "Will you forget me for living? Probably not.",  // Dehumaniser - After All
            "Using souls from Hell to kill demons. In Hell. Sure?",
            "Live like a god, die like a god.",
        },
        {
            "Flechettes! Find some centaurs!",
            "Expiration dates are just suggestions. Drink it anyway.",
            "This is just a fart in a flask!",
            "Do not attempt to drink.",
            "Do you want to know how long this has been fermenting?",
            "Brought to you by Mace Cologne-inna-bottle for Gents!",
            "Don't yell 'Fire in the Hole'. Too cliche.",
            "I'm pretty sure this isn't a healing potion.",
            "No, it is not a protein shake.",
            "Grandma's special ingredient.",
        },
    },
    {
        {
            "I KICK YOO",
            "Balls of steel, meet boots of steel.",
            "Cossack dancers need not apply.",
            "Can Chuck Norris kick with both feet while running? Didn't think so.",
            "Liu Kang called, he wants his feet back.",
            "",
            "",
            "",
            "",
            "",
        },
        {
            "Pipe bombs! Find some unsuspecting saps!",
            "It's totally safe! Look at the warning stripes!",
            "Weren't expecting this in the mail, were you?",
            "I'm sure you really like your alt-fire being a kick right now.",
            "Illegal in about 37 states, but we'll make an exception for you.",
            "No givesies no backsies for life!",
            "And boom goes the dynamite.",
            "No longer bounces in midair.",
            "~~MLG 420 ALL DAY EVERY DAY~~",
            "No, not that pipe. No, not that smoking.",
        },
        {
            "Picked up a Glock 17.",
            "Counterpoint number 1.",
            "Yes I knew it was actually a Glock 17 I was just going off the Duke 3D port that gave it a name god damn I changed it are you happy?",
            "Did you think I was \cagone\c- forever?",
            "STOP HACKING.",
            "",
            "",
            "",
            "",
            "",
        },
        {
            "You got the Riot Shotgun!",
            "A demon invasion is a riot... kinda...",
            "You look like you're overheating. Lemme put some holes in you.",
            "The pigcops won't be missing this.",
            "FUCK DA POLICE",
            "Why have a battering ram when you can have a gun?",
            "Sniping with a shotgun? Why not?",
            "You got the Rito Shatgun!",
            "That's not the Duke insignia. The gun's just make out of plutonium.",
            "Oh my god, this game rips off Doom so much.",
        },
        {
            "You got the Explosive Shotgun!",
            "This'll satisfy my appetite for \cgDEATH\c-.",
            "Oh no, you're all over the walls! How ever did that happen?",
            "Hey, you know how explosives are shit at close range?",
            "Play dead, doggy. Good boy!",
            "Shoot with one hand, plug ears with the other.",
            "For the man with trouble expressing his emotions.",
            "Hey guys, I found some salsa dip!",
            "So, what kind of shells does this thing take?",
            "It makes a terrible hunting weapon.",
        },
        {
            "You got the Chaingun Cannon!",
            "Oh dear, you're coming apart at the seams!",
            "We're gonna need a mortician here in a little bit.",
            "Gonna rip 'em a new one.",
            "I got 99 problems, and you just stopped being one.",
            "This is why the janitors hate you, Duke.",
            "You need six barrels to kick less ass than me?",
            "Can we get someone who knows how to design a chaingun in here?!",
            "",
            "",
        },
        {
            "You got the RPG Launcher!",
            "When I'm through, the walls will be a memorial of your interiors.",
            "I'm going to go Quake on your ass.",
            "+2 to all Explosive checks.",
            "Can you help me with a mural? It's titled, \"The Very End of You\".",
            "It's turn-based. You go first.",
            "Pretty sure small explosions don't look like that.",
            "You store a gun... larger than your pants... in your pants. Okay.",
            "It's a pipe bomb! No, it's a rocket! Now it's an explosive shell!",
            "",
        },
        {
            "You got the Freezethrower!",
            "Stopped you dead in your tracks, didn't I?",
            "Didn't see that coming around the corner, huh?",
            "It's like a ice machine. With an automatic firing setting.",
            "It's all right, I needed some ice for my drink anyway.",
            "You don't get to keep it if your puns are terrible.",
            "You seem like an ice person.",
            "Where's the thawthrower?",
            "",
            "",
        },
        {
            "You got the Devastators! Hail to the King.",
            "Game over, chumps.",
            "Fun for the entire family.",
            "Rapid fire rockets with shotgun spread. Not OP at all.",
            "No one's gonna believe you store these in your pants too, Duke.",
            "You should just duct tape the triggers down.",
            "Michael Bay called, he wants to do a Presidential documentary.",
            "Also good for removing ingrown toenails!",
            "Lots of tiny mushroom clouds. What the hell kind of rockets are those?!",
            "Oh my god, this game rips off Duke Nukem Forever so much.",
        },
        {
            "You learned the ability to kick even faster!",
            "\cnLIU KANG MODE ENGAGED",
            "You're just jealous because you don't have an invisible bicycle.",
            "Now go run a marathon.",
            "Where the hell are my pipe bombs?!",
            "Of course, holding a gun up while doing this is impossible.",
            "",
            "",
            "",
            "",
        },
    },
    {
        {
            "I PUNCH YOO TOO",
            "Run sideways, oneshot imp. Got it.",
            "Tape slabs of steel to your fists. Works wonders IRL.",
            "Punch-Out! would've been so much better with these.",
            "Can gib zombiemen. Yes, please.",
            "Holy gibfist jesus!",
            "You picked up some steel blocks and an arc welder!",
            "",
            "",
            "",
        },
        {
            "A KKV-7 SMG and an extra .44 Magnum! Find some aliens!",
            "I'm gonna go cowboy on your ass.",
            "You thought one magnum was bad, huh?",
            "Bigger guns nearby.",
            "Everyone else gets melee weapons from this. I'm the only smart one here.",
            "pitpitpitpitpitpitpitpitpitpitpitpitpitpitpitpitpitpitpitpit",
            "With muzzle velocities this low, it's a wonder the gun can kill anything.",
            "",
            "",
            "",
        },
        {
            "Picked up a magnum.",
            "HOW I HOLD NOTHER PSITOL I DUNO LOL",
            "GUYS WHY CAN'T I DUAL WIELD",
            "20-28 damage is perfectly reasonable for a starting weapon.",
            "No, you can't actually use the scope. What, you think this is Halo?",
            "You rampant, hacking bastard.",
            "Destiny doesn't cheat.",
            "You probably want to waste the last three bullets in the mag before entering Super Mega Carnage Room.",
            "It's cool how you just made that gun appear out of nowhere, but you still have to kill the demons.",
            "",
        },
        {
            "You got the WSTE-M5 Combat Shotgun!",
            "I'm gonna make an expressway to your heart.",
            "Come closer, I'll help with your ventilation.",
            "I won't waste my time trying to explain the loading mechanism to you.",
            "One-handed? That's right.",
            "In the future, shotguns will still have bullets.",
            "Is there such thing as a non-combat shotgun?",
            "You hear the agonised screams of a coder in the distance.",
            "Why yes, having 90 damage at the pistol's fire rate is balanced.",
            "The only gun with a built-in gyroscope.",
        },
        {
            "You got the Zeus Class Fusion Pistol!",
            "Oh, you're invulnerable? That's cute.",
            "Your ass and face will be fused together in a little bit.",
            "Everyone's mortal but me.",
            "And they said this was useless.",
            "Looks like a taser, but ha ha no it's not.",
            "What's that? Stop shooting? Why?",
            "I hope you weren't expecting that shield to work.",
            "This pretty much wrecks Strife. Just sayin'.",
            "Who knew something as expensive as nuclear fusion would be so energy-efficient?",
        },
        {
            "You got the MA-75B Assault Rifle!",
            "I'll suppress you forever.",
            "That grenade to the face was for talking back.",
            "Eat it, vid boi.",
            "I'm a bit full on bullets. Want some?",
            "Standard issue for every single space marine ever.",
            "Accuracy is compensated for with more shooting.",
            "Turns out that chaingun had some grenades too. Neat.",
            "The previous model was a chaingun, by the way.",
            "Hopeless encounters successfully won. Big guns probably helped.",
        },
        {
            "You got the SPNKR-XP SSM Launcher!",
            "Frog blast the vent core!",
            "Do I really need two chances to smear you?",
            "Charon doesn't make change.",
            "There is no \"almost\" with dodging this.",
            "Can someone give me a boost, I can't see over this thing.",
            "Well, I have a rocket launcher...",
            "Backblast is for lesser men to worry about.",
            "Why do you always go where I want and do what I say?",
            "Oh my god this game rips off Halo so much.",
        },
        {
            "You got the TOZT-7 Napalm Unit!",
            "Who wants a barbeque?",
            "Super shotgun? That's cute. Lemme see it.",
            "Smells like napalm, tastes like chicken.",
            "You cold? I'll warm you up.",
            "Despite all your fancy future tech, fire's still pretty good.",
            "You are really good at killing things. I'm impressed.",
            "Hundreds of years in the future, fire is still hot.",
            "If you're stuck here, you better go ask your mom.",
            "That's a clean-burning hell, I'll tell you what.",
        },
        {
            "You got the ONI-71 Wave Motion Cannon! What's that spell? Trouble.", // since apparently this quote ain't good enuf
            "I'm returning you to the store in a coffee tin.",
            "You'll be long gone by the time you see it.",
            "For carnage, apply within.",
            "It makes a \caterrible\c- melee weapon.",
            "I could aim. But with this thing, I don't have to.",
            "Your brand new favorite ONI-chan.",
            "I'm sure its list of lives taken would bore you, so get back to work.",
            "By the way, I had an accident with a tank while you were away. Here's the turret.",
            "P.S. If things around here aren't working, it's because I'm laughing so hard.",
        },
        {
            "You got the Tech.50 Pacifier!",
            "It does \canot\c- go in your mouth.",
            "I dunno, it sure doesn't pacify me.",
            "The only weapon a security officer would reasonably have!",
            "I'm sure you will use this purely for security purposes.",
            "Looks like a funky fusion pistol.",
            "Wait a second, this isn't a camera!",
            "",
            "",
            "",
        },
    },
    {
        {
            "I CLEAVE YOO",
            "Standard weaponry for all personnel: a fuckoff axe. Sounds reasonable.",
            "You know you should probably wipe the blood off, right?",
            "It keeps you standing upright, or else.",
            "I'd be angry too if I had to carry around a giant axe everywhere. Shit's heavy.",
            "It makes a terrible bottle opener.",
            "Should probably find a whack sound closer to Quake someday, but... eh.",
            "So of all weapons, why did you cheat for this one?",
            "Careful now, you might actually kill someone with it!",
            "Y'know, it had blood on it when you got it. Who does that blood belong to?",
        },
        {
            "Mjolnir! Find some grunts!",
            "You got a Hammer that shoots lightning. omg thor",
            "The lightning works best when it's inside a wall.",
            "You never did take that athpirin, did you.",
            "So, uh, whose bone is that anyway?",
            "It makes a terrible letter-opener.",
            "Aiming at the floor is actually more effective.",
            "This doesn't use ammo, you poo-poo bums. My immersion is now ruined forever.",
            "Don't buy your Norse hammers from Wal-Mart, people.",
            "Get out of here, you Parias wannabe!",
        },
        {
            "Picked up a shotgun. This one feels inferior, somehow.",
            "I'm gonna telefrag your hacking butt.",
            "Note that you never pump it.",
            "If a single shotgun meets another single shotgun, do they become engaged shotguns?",
            "Clearly the best shotgun in Samsara.",
            "DID YOU KNOW: Originally, Ranger was a Norse god wannabe whose name was Quake. Hence the name.",
            "Most realistic shotgun spread in this mod. Least realistic shotgun damage.",
            "A shotgun? As opposed to what, a banggun?",
            "Ranger, thou art a immense bitch to balance. Stop that.",
            "Whoever made the helmets really should've added faceplates.",
        },
        {
            "You got the double-barreled shotgun!",
            "Where does the other shell come from? My arse.",
            "Works like your mouse, just point and click.",
            "It's totally not the super shotgun. It's shittier, for one.",
            "When you just need a little extra bass.",
            "Insert witty comment here.",
            "The second barrel is there to confuse you.",
            "Watch those shells just pile up.",
            "\caHA HA HA ACTUALLY PUTTING SHELLS IN THE GUN.",
            "Shells are stupid anyway.",
        },
        {
            "You got the grenade launcher!",
            "Guaranteed to make friends with campers.",
            "Should have cut out those fuses ahead of time.",
            "It's like a pitching machine from hell. And brown. And explosive.",
            "Like skipping rocks except with more dismemberment.",
            "Do not taunt the happy fun ball.",
            "Going into melee is not advised.",
            "\caHOLY CRAP IT BOUNCES.",
            "And just how in the hell did you fit 15 grenades into there?",
            "... where's the rockets?",
        },
        {
            "You got the nailgun!",
            "What construction is this good for?",
            "What's next, a belt sander?",
            "It's a carpenter! Run for your lives!",
            "Hush. Bullets are expensive.",
            "Threaten them with your son's arts and crafts project.",
            "It also fires lava. Shaped into nails. Shut up.",
            "I'm just going to build a casket for you!",
            "Who manufactures nails with propellant?",
            "Someone lost a job over this.",
        },
        {
            "You got the rocket launcher!",
            "Is this deathmatch? Time to forget about everything else.",
            "Useful for reaching the top shelf.",
            "The only travel method suggested by one out of five doctors!",
            "That's what your feet get for talking back.",
            "You never liked that toe anyway.",
            "Warning: May be hazardous to health.",
            "Smells like Aerowalk.",
            "And then balance happened.",
            "Make them ride your rocket. Make them like it.",
        },
        {
            "You got the Super Nailgun!",
            "You people better appreciate this.",
            "No, really, you better fucking appreciate it.",
            "It's like a chaingun for hardware enthusiasts.",
            "But... but... it shot lightning just two minutes ago.",
            "The blue finish is why it does more damage.",
            "Time to completely ignore the normal nailgun.",
            "This is the best you have for sniping.",
            "What are you gonna do, repair me to death?",
            "Who designs a rotary nailgun?!",
        },
        {
            "You got the Quad Damage and Thunderbolt! Gib everything.",
            "Oh good. I've always wanted to tear people in half with lightning.",
            "Why can't I hold all these kills?",
            "You have a gun that fires instant death lightning. omg techthor",
            "Why do I destroy everything I touch? ;_;",
            "For a last ditch effort, you can stab people with the nail.",
            "You can't spell Genocide with a Q, silly.",
            "You're like King Midas. But with gibs instead of gold.",
            "Atop the tallest of earth's peaks dwell the gods of earth, and suffer not man to tell that he hath looked upon them.",
            "Guaranteed to make balancing efforts fall apart, or your money back.",
        },
        {
            "You got the gauntlet!",
            "This is from Quake 3, you poo-poo bums. My immersion is now ruined forever.",
            "It came back ;_;",
            "But can it blend?",
            "Also doubles as a high-risk pizza cutter.",
            "Maybe strapping this onto your arm wasn't the best of ideas.",
            "Wait 'til you see the belt sander in the thigh pads.",
            "It's not the best boxing glove in the world, but it's trying.",
            "Great for the kitchen, too.",
            "Brass knuckles? Real men use stainless serrated steel buzzsaws.",
        },
    }
};


int ClassUniqueMessages[CLASSCOUNT][MSGCOUNT] =
{
    {
        "Berserk!",
        "Rip and tear! Rip and tear your guts!",
        "Oooh, here comes the night train!",
        "I'm the man! I'm superbad!",
        "The quickest way to a man's heart is through their chest.",
        "Someone spiked the punch.",
        "You got a black box with a cross on it. omg jesus",
        "Plot twist: you were Baratus all along.",
        "You touched it with your feet, though...",
        "",
    },
    {
        "Supercharge breakfast!",
        "OM NOM NOM NOM",
        "Because medikits are for wimps.",
        "Crunchy.",
        "Chex marks the spot!",
        "I'm sure it's still good. It's just been lying here.",
        "Is this cannibalism or what?",
        "It's milk you can chew!",
        "",
        "",
    },
    {
        "MORPH OVUM",
        "Parthoris Fried Chicken.",
        "Because nothing's better than turning an Archvile harmless.",
        "I'm calling fowl on this.",
        "Don't eat it.",
        "I'm sure there's hundreds of egg puns you can use.",
        "Omelettes, break some eggs, etc.",
        "",
        "",
        "",
    },
    {
        "You got an extra life!",
        "Maybe now you can go to college.",
        "Maybe one day this won't suck in Zandronum.",
        "One day, the villains will learn how to respawn, too.",
        "Now you can hug a demon with no repercussions.",
        "Good for the soul, too.",
        "BULLSHIT I HAD AN EXTRA LIFE WHY'D THE CYBERDEMON KILL ME",
        "",
        "",
        "",
    },
    {
        "MYSTIC AMBIT INCANT",
        "Heal plz.",
        "Warning: Not for use in deathmatch.",
        "A crowd on demand.",
        "Well, you're a cleric. Gotta have a heal.",
        "Plot twist: it's a badly-inscribed poison spell.",
        "",
        "",
        "",
        "",
    },
    {
        "JETPACK!",
        "I believe I can touch the sky.",
        "Guaranteed to make friends with mappers.",
        "And this is why Virus will never be in.",
        "Because you have that on your sprite for a reason.",
        "Watch your ass, the jet burns.",
        "The gas mileage is \caterrible\c-.",
        "",
        "",
        "",
    },
    {
        "You got th@nS0-.'\casystem error \cd0xfded",
        "The difference between a room of aliens and a carpet of them.",
        "What fun to watch you work.",
        "~text interface term\cinal malfunction error \cd~2992dud",
        "your former self destroyed the dreaming way is eased",
        "down to the crushing center and spared the dance of forever",
        "This will allow you to kill more aliens. Does that make you happy?",
        "shedding all the weight of imagined moments and fear",
        "because fear is not the blood",
        "I know who you are.",
    },
    {
        "You got the laser cannon!",
        "This sounds like a weapon for soldiers who can't shoot straight.", // stormtroopers!
        "If this were in vanilla Quake, it would be slot 6. \ckbut alas",
        "This makes, what, five or six rapid fire weapons for Ranger?",
        "Are any of the weapon designs in Quake even practical?",
        "Do not aim at face. Not that it'll help.",
        "Does it come in blueberry?",
        "What is this, Star Wars?",
        "Bouncy red death!",
        "Pewpewlasers!",
    },
};

int PunchDrunkUniqueMessages[CLASSCOUNT][MSGCOUNT] =
{
    {
        "Berserk!",
        "Rip and tear! Rip and tear your guts!",
        "Oooh, here comes the night train!",
        "I'm the man! I'm superbad!",
        "The quickest way to a man's heart is through their chest.",
        "Someone spiked the punch.",
        "You got a black box with a cross on it. omg jesus",
        "Plot twist: you were Baratus all along.",
        "You touched it with your feet, though...",
        "",
    },
    {
        "Supercharge breakfast!",
        "OM NOM NOM NOM",
        "Because medikits are for wimps.",
        "Crunchy.",
        "Chex marks the spot!",
        "I'm sure it's still good. It's just been lying here.",
        "Is this cannibalism or what?",
        "It's milk you can chew!",
        "",
        "",
    },
    {
        "MORPH OVUM",
        "Parthoris Fried Chicken.",
        "Because nothing's better than turning an Archvile harmless.",
        "I'm calling fowl on this.",
        "Don't eat it.",
        "I'm sure there's hundreds of egg puns you can use.",
        "Omelettes, break some eggs, etc.",
        "",
        "",
        "",
    },
    {
        "You got the Spear of... Longinus?",
        "You know you're supposed to throw this too, right?",
        "... just like my knife. Why do I need this?",
        "pew pew pew pew pew pew pew",
        "It makes a terrible sewing needle.",
        "Maybe the dollar store wasn't the best place to look.",
        "Poke of Kill That Thing In Front Of You.",
        "Next up, the Spear of Carl From Next Door.",
        "",
        "",
    },
    {
        "SPIKED GAUNTLET",
        "Sure was nice of Baratus to lend a hand.",
        "Swear to God, first person who makes a 'throwing the gauntlet' pun...",
        "Rule with this.",
        "Well, you're a cleric of metal. Gotta head-bang.",
        "Axe in one hand, gauntlet in the oth--wait, what do you mean I can't?!",
        "I like the church that gives their priests punching lessons.",
        "I love the Power Glove. It's so bad.",
        "God power keeps my pimp hand strong!",
        "Hand, awesome power, burning grip, etc.",
    },
    {
        "NUKEBOOT!",
        "This is not what they meant by Atomic Edition.",
        "Next up, black hole brass knuckles.",
        "I can't rocket jump off them this is so unrealistic ;_;",
        "It's nothing compared to your farts.",
        "Great for soccer, too!",
        "Your running is now a military secret.",
        "Comes with built-in earplugs.",
        "Being able to see when using this? That's dumb.",
        "",
    },
    {
        "You got the Talon Ceramic Combat Blade!",
        "For being a ceramic, it can sure handle bouncing off walls pretty well.",
        "It makes a terrible butter knife.",
        "Thousands of years into the future, sharp things still hurt.",
        "You'll put an eye out with it.",
        "So, how indebted are we to Hopper by now?",
        "Don't ask the probabilities of a knife bouncing like this.",
        "I set my blenders to 'juicy'.",
        "A murderer has been chosen... \cg...AND IT'S YOU!",
        "Thousands of years in the future, bathroom tiling makes the best weapons.",
    },
    {
        "You got Mjolnir!",
        "You got a Hammer that shoots lightning. omg thor",
        "The lightning works best when it's inside a wall.",
        "You never did take that athpirin, did you.",
        "So, uh, whose bone is that anyway?",
        "It makes a terrible letter-opener.",
        "Aiming at the floor is actually more effective.",
        "This doesn't use ammo, you poo-poo bums. My immersion is now ruined forever.",
        "Get out of he... okay, I guess you can stay. You're still a stupid Parias wannabe.",
        "Hammertime.",
    },
};


// jesus fucking christ, 1200 lines
