#define MSGCOUNT 5

int ClassPickupMessages[CLASSCOUNT][SLOTCOUNT][MSGCOUNT] = 
{
    {
        {
            "I PUNCH YOO",
            "\cgRIP AND TEAR",
            "Fuck your handshakes.",
            "",
            "",
        },
        {
            "A chainsaw! Find some meat!",
            "The great communicator!",
            "Groovy.",
            "",
            "",
        },
        {
            "Picked up a pistol.",
            "Hey, useless!",
            "The most useless pistol in this mod.",
            "",
            "",
        },
        {
            "You got the Shotgun!",
            "Might makes light!",
            "",
            "",
            "",
        },
        {
            "You got the Super Shotgun!",
            "And I feel mighty!",
            "The only Slot 3 allowed to get away with 200 damage.",
            "",
            "",
        },
        {
            "You got the Chaingun!",
            "Hey, chaingun! The hell with respect!",
            "",
            "",
            "",
        },
        {
            "You got the Rocket Launcher!",
            "The sugar-sweet kiss of heavy ordinance!",
            "Still the best rocket jumping tool.",
            "",
            "",
        },
        {
            "You got the Plasma Rifle!",
            "Sweet christmas! It's always something!",
            "All reet then! I'm all about this plasma rifle!",
            "I'm all about this plasma rifle! And baby, it's all about me!",
            "",
        },
        {
            "You got the BFG9000! Oh, yes.",
            "Hail to the chief!",
            "... and my gun is very, very large.",
            "",
            "",
        },
    },
    {   // yeah I really didn't have ideas for this one
        {
            "I SCOOP YOO",
            "\cdPOUR AND SHARE",
            "",
            "",
            "",
        },
        {
            "A Super Bootspork! Find some milk!",
            "I'm pretty sure this wasn't made for boots.",
            "I will scoop out your organs and serve them for breakfast.",
            "",
            "",
        },
        {
            "Picked up a Mini Zorcher.",
            "Hey, useless zappy thing!",
            "",
            "",
            "",
        },
        {
            "You got the Large Zorcher!",
            "Why do zappy things need spread again?",
            "",
            "",
            "",
        },
        {
            "You got the Super Large Zorcher!",
            "Bouncy death in a white box!",
            "",
            "",
            "",
        },
        {
            "You got the Rapid Zorcher!",
            "Wasn't this an eggbeater?",
            "",
            "",
            "",
        },
        {
            "You got the Zorch Propulsor!",
            "No rocket jumping for you.",
            "",
            "",
            "",
        },
        {
            "You got the Phasing Zorcher!",
            "Zappy red things!",
            "",
            "",
            "",
        },
        {
            "You got the LAZ Device! Woot!",
            "The pinnacle of science. Giant red blobs of zap.",
            "",
            "",
            "",
        },
    },
    {
        {
            "I JAB YOO",
            "\cfBEAT AND PARRY",
            "Occasionally makes blue explosions where it hits.",
            "",
            "",
        },
        {
            "Gauntlets of the Necromancer! Find some disciples!",
            "The gloves your gloves wish they were.",
            "I powered these up, can I have your HP now?",
            "",
            "",
        },
        {
            "Picked up a gold wand.",
            "Hey, useless crystal thing!",
            "",
            "",
            "",
        },
        {
            "You got the Firemace!",
            "And you thought this was Slot 7.",
            "From useless to overpowered in one certain book.",
            "",
            "",
        },
        {
            "You got the Ethereal Crossbow!",
            "Aren't crossbows meant to be accurate?",
            "Oh my god this thing rapes when powered up.",
            "",
            "",
        },
        {
            "You got the Dragon Claw!",
            "So apparently dragons are walking miniguns?",
            "Claws don't bend inward. What the fuck, evolution?",
            "",
            "",
        },
        {
            "You got the Phoenix Rod!",
            "Also doubles as a shitty coat rack.",
            "Flip someone the bird tonight.",
            "",
            "",
        },
        {
            "You got the Hellstaff!",
            "It's too close to a plasma rifle. UAC's gonna sue.",
            "Like the plasma rifle, but shittier in every way.",
            "Time to rain on someone's parade.",
            "",
        },
        {
            "You got the Tome of Power! Ahahaha...",
            "Fuck BFG, we'll make \caeverything\c- overpowered.",
            "Well, show's over I guess.",
            "",
            "",
        },
    },
    {
        {
            "I STAB YOO",
            "\cgSTAB AND SPAR",
            "",
            "",
            "",
        },
        {
            "Your knife developed teeth! Find some Nazis!",
            "Now \cathis\c- is a knife!",
            "You can bring this one to a gun fight.",
            "",
            "",
        },
        {
            "Picked up a Luger.",
            "Hey, sniper useless!",
            "",
            "",
            "",
        },
        {
            "You got the Machine Gun!",
            "Shotgun? Fuck off, I've got a machine gun.",
            "Basically a faster, weaker sniper rifle.",
            "",
            "",
        },
        {
            "You got the Machine Gun!",
            "Super shotgun? Ahahaha no.",
            "Well, time to stay the hell away from the dude with the SSG.",
            "",
            "",
        },
        {
            "You got the Chaingun!",
            "If this were Wolfenstein 3D, you'd just have hit top tier.",
            "A constant beam of death from any range. Not bad.",
            "",
            "",
        },
        {
            "You got the Rocket Launcher!",
            "You got the Zreep Gun!",
            "I don't think Wolfenstein 3D got rocket launchers.",
            "",
            "",
        },
        {
            "You got the Flamethrower!",
            "Because flamethrowers have infinite range.",
            "So apparently the Hitler vampires were packing flamethrowers.",
            "",
            "",
        },
        {
            "You got the Spear of Destiny! Heaven awaits.",
            "Buttered popcorn, straight from Jesus.",
            "Delicious overpoweredness. What more could you want?",
            "",
            "",
        },
    },
    {
        {
            "I WAK YOO",
            "\cfPOUND AND SMEAR",
            "",
            "",
            "",
        },
        {
            "Flechettes! Find some centaurs!",
            "Mexican burritos would be more effective.",
            "This is just a fart in a flask!",
            "",
            "",
        },
        {
            "Picked up a sapphire wand.",
            "Hey, actually slightly useful!",
            "This is all you need to slaughter Korax.",
            "",
            "",
        },
        {
            "You got the Frost Shards!",
            "You got the Massive Weapon Frost-wait what.",
            "\caYOU ARE NOW \cnICICLE",
            "",
            "",
        },
        {
            "You got Timon's Axe!",
            "Because whacking people with an axe needs lightning.",
            "Well, you'd be in melee range \caanyway\c-...",
            "",
            "",
        },
        {
            "You got the Serpent Staff!",
            "\caCLERIC SAPPIN MAH CENTAUR\c-",
            "Serpents are secretly vampires. Got it.",
            "",
            "",
        },
        {
            "You got the Hammer of Retribution!",
            "Infinite amounts of exploding hammers. Okay then.",
            "I think this weapon breaks the law of conservation of mass.",
            "",
            "",
        },
        {
            "You got the Firestorm!",
            "Literal baptism by fire.",
            "You wish fireball spells were this manly.",
            "",
            "",
        },
        {
            "You got the Wraithverge! Scream for me!",
            "Still less powerful than a fart cloud.",
            "Ahahahaha aiming. Fuck that.",
            "",
            "",
        },
    },
    {
        {
            "I KICK YOO",
            "Balls of steel, meet boots of steel.",
            "",
            "",
            "",
        },
        {
            "Pipe bombs! Find some unsuspecting saps!",
            "Enjoy \cathis\c- present.",
            "Weren't expecting this in the mail, were you?",
            "",
            "",
        },
        {
            "Picked up an M1911.",
            "Counterpoint number 1.",
            "",
            "",
            "",
        },
        {
            "You got the Riot Shotgun!",
            "I hope you like buckshot for lunch.",
            "You look like you're overheating. Lemme put some holes in you.",
            "",
            "",
        },
        {
            "You got the Explosive Shotgun!",
            "This'll satisfy my appetite for \cgDEATH\c-.",
            "Oh no, you're all over the walls! How ever did that happen?",
            "",
            "",
        },
        {
            "You got the Chaingun Cannon!",
            "Oh dear, you're coming apart at the seams!",
            "We're gonna need a mortician here in a little bit.",
            "",
            "",
        },
        {
            "You got the RPG Launcher!",
            "When I'm through, the walls will be a memorial of your interiors.",
            "I'm going to go Quake on your ass.",
            "",
            "",
        },
        {
            "You got the Freezethrower!",
            "Stopped you dead in your tracks, didn't I?",
            "Didn't see that coming around the corner, huh?",
            "",
            "",
        },
        {
            "You got the Devastators! Hail to the King.",
            "Game over, chumps.",
            "Fun for the entire family.",
            "",
            "",
        },
    },
    {
        {
            "I PUNCH YOO TOO",
            "Run sideways, oneshot imp. Got it.",
            "",
            "",
            "",
        },
        {
            "A KKV-7 SMG and an extra .44 Magnum! Find some aliens!",
            "I'm gonna go cowboy on your ass.",
            "You thought one magnum was bad, huh?",
            "",
            "",
        },
        {
            "Picked up a magnum.",
            "HOW I HOLD NOTHER PSITOL I DUNO LOL",
            "",
            "",
            "",
        },
        {
            "You got the WSTE-M5 Combat Shotgun!",
            "I'm gonna make an expressway to your heart.",
            "Come closer, I'll help with your ventilation.",
            "",
            "",
        },
        {
            "You got the Zeus Class Fusion Pistol!",
            "Oh, you're invulnerable? That's cute.",
            "Your ass and face will be fused together in a little bit.",
            "",
            "",
        },
        {
            "You got the MA-75B Assault Rifle!",
            "I'll suppress you forever.",
            "That grenade to the face was for talking back.",
            "",
            "",
        },
        {
            "You got the SPNKR-XP SSM Launcher!",
            "The janitors will hate me today.",
            "Do I really need two chances to smear you?",
            "",
            "",
        },
        {
            "You got the TOZT-7 Napalm Unit!",
            "Who wants a barbeque?",
            "Super shotgun? That's cute. Lemme see it.",
            "",
            "",
        },
        {
            "You got the ONI-71 Wave Motion Cannon! What's that spell? Trouble.", // since apparently this quote ain't good enuf
            "I'm returning you to the store in a coffee tin.",
            "You'll be long gone by the time you see it.",
            "",
            "",
        },
    },
};
